package org.vmstudio.visor.api.common.network;

public enum VisorPayloadID {
    HANDSHAKE,
    SERVER_SETTINGS,
    FULL_HEIGHT,
    POSE_DATA,
    VR_BODY_TYPE,
    LEFT_HANDED,
    ACTIVE_HAND,
    OFFHAND_SLOT,
    WORLD_SCALE,
    GUN_ANGLE,
    ROTATION_Y,
    CRAWLING,
    CLIMBING,
    TELEPORT,
    SWING_ATTACK,
    SWING_BLOCK,
    BLOCK_DAMAGE,
    GUI_STATE,
    OTHER_VR_GUI_STATE,
    OTHER_VR_POSE_DATA,
    OTHER_VR_LEFT_HANDED,
    OTHER_VR_BODY_TYPE,
    OTHER_VR_WORLD_SCALE,
    OTHER_GUN_ANGLE,
    OTHER_VR_FULL_HEIGHT
}
